name: build workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm install
        - name: first step
          run: npm run lint
        - name: second step
          run: npm run test
        - name: third step
          run: npm run build

            
